### ISSUE TITLE
Cant Restore Cluster with global init scripts

### ISSUE THREAD

**Issue by coreystokes-8451** [databrickslabs/databricks-sync#117]
Hello @stikkireddy 

We cannot restore clusters that have global init scripts attached to them:

```
Error: Reference to undeclared resource
2022-10-05 16:07:18 [INFO] │
2022-10-05 16:07:18 [INFO] │   on databricks_cluster_1005_200229_5rxceiqg.tf.json line 12, in resource.databricks_cluster.databricks_cluster_1005_200229_5rxceiqg.depends_on:
2022-10-05 16:07:18 [INFO] │   12:                     "databricks_global_init_script.databricks_global_init_scripts"
2022-10-05 16:07:18 [INFO] │
2022-10-05 16:07:18 [INFO] │ A managed resource "databricks_global_init_script"
2022-10-05 16:07:18 [INFO] │ "databricks_global_init_scripts" has not been declared in the root module.
2022-10-05 16:07:18 [INFO] ╵
```

**Comment by coreystokes-8451** [comment]
Yes, they are included in the yamL

```
global_init_script:
    # pattern will be implemented in the future - make sure you have "*" in here
    patterns:
      - "*"
```

I am using version 0.3.1 of the tool

**Comment by stikkireddy** [comment]
do you actually have global init scripts in your workspace? If not this could cause an error.

**Comment by coreystokes-8451** [comment]
Yes global init script exist in the workspace

**Comment by stikkireddy** [comment]
hey sorry was traveling over the week. I will get back to you by Monday if I can recreate this issue on my end.

**Comment by coreystokes-8451** [comment]
@stikkireddy Hey is there any update ?

**Comment by stikkireddy** [comment]
@coreystokes-8451 i tried a few combinations and i was not able to recreate this issue on my side. 
<img width="404" alt="image" src="https://user-images.githubusercontent.com/54602805/197047361-8a0a5bd0-cb6c-4ad6-937a-7e3790dc6b93.png">
Do you see anything here for global init scripts?

**Comment by coreystokes-8451** [comment]
@stikkireddy  Yes a global init scrip folder exists with Terraform code

**Comment by stikkireddy** [comment]
umm can you open the file and see if its an empty file? in terms of the foreach?

**Comment by coreystokes-8451** [comment]
@stikkireddy  Heres the contents of the file
```
{
    "locals": {
        "databricks_global_init_scripts_for_each_var": {
            "A0624D40C9AD1DEB": {
                "enabled": true,
                "name": "init-artifactory-KRGDMP-access",
                "position": 0,
                "source": "${pathexpand(\"databricks_global_init_script_init_artifactory_KRGDMP_access_A0624D40C9AD1DEB\")}"
            }
        }
    },
    "resource": {
        "databricks_global_init_script": {
            "databricks_global_init_scripts": {
                "enabled": "${each.value.enabled}",
                "for_each": "${local.databricks_global_init_scripts_for_each_var}",
                "name": "${each.value.name}",
                "position": "${each.value.position}",
                "source": "${each.value.source}"
            }
        }
    }
}
```

**Comment by stikkireddy** [comment]
hmm i am not able to recreate this issue on my side. Looks like the name is correct and valid maybe can you ping your databricks contact and maybe we can get on a quick call? I tried a few different combinations. Tomorrow or monday?

**Comment by coreystokes-8451** [comment]
Closing, it is recommended to restore an entire workspace rather than individual pieces
